name: Build and Push Docker Webapp image

on:
  workflow_dispatch:
  #push:
    #branches: [ "main" ]

jobs:

  build:
  
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out code
      uses: actions/checkout@v2
      
    - name: Build WebApp Docker image
      run: docker build --file "${{ github.workspace }}/OSDC.UnitConversion.DrillingUnitConversion.WebApp.Client/Dockerfile" --tag digiwells/osdcunitconversiondrillingunitconversionwebappclient:stable .

    - name: Login to DockerHub
      run: docker login -u="${{ secrets.DOCKERHUB_USERNAME }}" -p="${{ secrets.DOCKERHUB_PASSWORD }}"
        
    - name: Push images to DockerHub
      run: |
        docker push digiwells/osdcunitconversiondrillingunitconversionwebappclient:stable
